import {
  connect,
  get as _get,
  Wrapper,
  reduxWrapper,
  configure,
  Markdown
} from 'eventjuicer-site-components';

const settings = require('../../settings').default;


const PageLegalVisitors = () => (

 
        <Wrapper first label="visitors.agreement.title">
        <Markdown>{`

# Rules for participants (Terms and conditions of ordering access to the online event)
             
### 1. Definitions

1.1 The Organizer - E-Commerce Capitals spółka z ograniczoną odpowiedzialnością sp. k. (E-Commerce Capitals limited liability company limited partnership) with its registered seat in Poznan, Poland, Botaniczna St. No. 26/2, 60-586 Poznan, entered in the Register under the number KRS 0000592712, NIP 7792439665, REGON 363746333, which registration files are kept by the District Court Poznan - Nowe Miasto and Wilda in Poznan, VIII Commercial Division of the National Court Register (Sąd Rejonowy Poznań – Nowe Miasto i Wilda w Poznaniu VIII Wydział Gospodarczy Krajowego Rejestru Sądowego)

1.2 Service – the Internet service available on the Internet at www.virtual.ecommerceberlin.com, under which the administrator enables to use the Application for ordering the Access to the online streaming.

1.3 The Application - the system available through the Service where the User can order the Access to the online streaming.

1.4 The Event – an event organized or co-organized by the Organizer, the information on which is included in the Service - in particular on the organization and accessibility hours for participants.

1.5 The Access - an online access link ordered through the Application and free of charge generated by the Organizer, authorizing, to a single entry as a participant to the Event on the day of its organization.

1.6 User - a natural person who has at least limited legal capacity, which uses the Application for any purpose, including, in particular in order to receive an Access.

### 2. General Provisions

2.1 The Organizer provides the following email address: hello@ecommerceberlin.com, intended for staying in contact with him, in particular to report problems with the use of the Application and any irregularities related to ordering Access.

2.2 To properly use the Application and order the Access one must have a device connected to the Internet that enables to use its resources and have an active email account.

2.3 Use of the Service and the Application is free.

### 3. Order of the Access

3.1 To order the Access on the subpage of the Service at http://virtual.ecommerceberlin.com one must complete the registration form including the following information: email address, first name, surname, job title, brand name, How the User did hear about the Event, mobile no., and then click "Register".

3.2 By clicking "Register" the User simultaneously accepts these terms and conditions.

3.3 The ordered Access will be sent no later than one day before the Event to the email address provided by the User in the form.

### 4. The Access and admission to the Event

4.1 The Access is the only document valid for taking part in the Event in the hours of access for participants.

4.2 The Access entitles to join to the Event only a person who received a registration confirmation e-mail.

4.3 In order to enter the Event the Ticket must be printed and presented at the entrance to a person authorized by the Organizer to control the Ticket along with identity cards including data complying with the data on the Ticket (name and surname).

4.4 Persons not having a registration confirmation e-mail will not be admitted to the Event.

4.5 Persons joining the Event are obliged to comply with the Terms and conditions for the participants.

### 5. Technical problems and complaints.

5.1 Any technical problems and complaints related to the operation of the Service and the Application should be submitted to the Organizer at the email address given in Section 2.1.

5.2 Organizer immediately, not later than 14 days from the date of receipt of the notification, shall respond by sending an e-mail to the address from which he received the notification.

### 6. Personal data

All information about personal data protection and privacy one can find here in our​​ ​https://virtual.ecommerceberlin.com/legal/visitors-data Information about personal data protection

## 7. Final provisions

7.1 These terms and conditions are available on the http://virtual.ecommerceberlin.com/visitor-rules, and in the Organizer's office.

7.2 Administrator allows anyone to download these terms and conditions and save them on his own data carrier.


        `}</Markdown>
        </Wrapper>
     
)



export const getStaticProps = reduxWrapper.getStaticProps(async (props) => {

  return await configure(props, {
    settings: settings,
    cache: 600
  });

})

export default connect()(PageLegalVisitors);
