import {
  connect,
  get as _get,
  // Typography,
  Wrapper,
  reduxWrapper,
  configure
} from 'eventjuicer-site-components';

const settings = require('../../settings').default;


const PageLegalVisitors = () => (

 
        <Wrapper first label="visitors.agreement.title">
          <div
            dangerouslySetInnerHTML={{
              __html: `<div>
                
                <h2>Rules for visitors <small>Terms and conditions of ordering tickets</small></h2>
             
                <section>
            
                <p><strong>1. Definitions</strong></p>
                <p><strong>1.1 The Organizer</strong> - E-Commerce Capitals spółka z ograniczoną odpowiedzialnością sp. k. (E-Commerce Capitals limited liability company limited partnership) with its registered seat in Poznan, Poland, Jan Matejko St. No. 52/4, 60-770 Poznan, entered in the Register under the number KRS 0000592712, NIP 7792439665, REGON 363746333, which registration files are kept by the District Court Poznan - Nowe Miasto and Wilda in Poznan, VIII Commercial Division of the National Court Register (Sąd Rejonowy Poznań – Nowe Miasto i Wilda w Poznaniu VIII Wydział Gospodarczy Krajowego Rejestru Sądowego)</p>
                <p><strong>1.2 Service</strong> – the Internet service available on the Internet at www.ecommerceberlin.com, under which the administrator enables to use the Application for ordering the Ticket.</p>
                <p><strong>1.3 The Application</strong> - the system available through the Service where the User can order the Ticket.</p>
                <p><strong>1.4 The Event</strong> – an event organized or co-organized by the Organizer, the information on which is included in the Service - in particular on the organization and accessibility hours for visitors.</p>
                <p><strong>1.5 Ticket</strong> - an electronic document ordered through the Application and free of charge generated by the Organizer, authorizing, after printing and presentation, to a single entry as a visitor to the Event on the day of its organization.</p>
                <p><strong>1.6 User</strong> - a natural person who has at least limited legal capacity, which uses the Application for any purpose, including, in particular in order to generate the Ticket.</p>
                <p><strong>2. General Provisions</strong></p>
                <p>2.1 The Organizer provides the following email address: hello@ecommerceberlin.com, intended for staying in contact with him, in particular to report problems with the use of the Application and any irregularities related to ordering Tickets.</p>
                <p>2.2 To properly use the Application and order the Ticket one must have a device connected to the Internet that enables to use its resources and have an active email account.</p>
                <p>2.3 Use of the Service and the Application is free.</p>
                <p><strong>3. Order of the Ticket</strong></p>
                3.1 To order the Ticket on the subpage of the Service at http://ecommerceberlin.com one must complete the registration form including the following information: email address, first name, surname, job title, brand name, How the User did hear about the Event, mobile no., and then click "Save".<p></p>
                3.2 By clicking "Save" the User simultaneously accepts these terms and conditions.<p></p>
                3.3 The ordered Ticket will be sent no later than two days before the Event (in pdf format) to the email address provided by the User in the form.<p></p>
                <p><strong>4. The Ticket and entrance to the Event.</strong></p>
                <p>4.1 The Ticket is the only document valid for entry to the Event in the hours of access for visitors.</p>
                <p>4.2 The Ticket entitles to entry to the Event only a person whose details (name and surname) are shown on the Ticket.</p>
                <p>4.3 In order to enter the Event the Ticket must be printed and presented at the entrance to a person authorized by the Organizer to control the Ticket along with identity cards including data complying with the data on the Ticket (name and surname).</p>
                <p>4.4 Persons not having printed Ticket and persons, whose data from the identity card does not match the information on the Ticket will not be admitted to the Event.</p>
                <p>4.5 Persons entering the Event are obliged to comply with the Terms and conditions for the visitors.</p>
                <p><strong>5. Technical problems and complaints.</strong></p>
                <p>5.1 Any technical problems and complaints related to the operation of the Service and the Application should be submitted to the Organizer at the email address given in Section 2.1.</p>
                <p>5.2 Organizer immediately, not later than 14 days from the date of receipt of the notification, shall respond by sending an e-mail to the address from which he received the notification.</p>
                <p><strong>6. Personal data</strong></p>
                <p>All information about personal data protection and privacy one can find here in our​​ ​<a href="https://ecommerceberlin.com/legal/visitors-data">Information about personal data protection</a>
                </p>
                <p><strong>7. Final provisions</strong></p>
                <p>7.1 These terms and conditions are available on the http://ecommerceberlin.com/visitor-rules, and in the Organizer's office.</p>
                <p>7.2 Administrator allows anyone to download these terms and conditions and save them on his own data carrier.</p>
               
                </section>
                </div>`,
            }}
          />
        </Wrapper>
     
)



export const getStaticProps = reduxWrapper.getStaticProps(async (props) => {

  await configure(props, {
    settings: settings,
    //preload: [""]
  });

  return {props: {}, revalidate: 600}

})

export default connect()(PageLegalVisitors);
